### ISSUE TITLE
Create 1st draft of Map Guide

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/tribal-water-data-map-manual#1]
Link to [Map Guide](https://cawaterboarddatacenter.github.io/tribal-water-data-map-manual/map-guide.html)

@Josh-d89 - once you have finished the draft, @ me back in here and I will review. Go team! :)

**Comment by Josh-d89** [comment]
@AHolder1 super weird. It's pushing to Github but not on the website. Plzzzz help!
