### ISSUE TITLE
Add groundwater/aquifer layer

### ISSUE THREAD

**Issue by Josh-d89** [CAWaterBoardDataCenter/tribal-water-data-map-manual#11]

**Comment by Lbenton114** [comment]
https://data.ca.gov/dataset/i08-b118-ca-groundwaterbasins
https://gis.water.ca.gov/app/bbat/

**Comment by kevinjsong** [comment]
Added with DWR data download: https://water.ca.gov/programs/groundwater-management/bulletin-118
