### ISSUE TITLE
Add DPR Mapping Information layer

### ISSUE THREAD

**Issue by Josh-d89** [CAWaterBoardDataCenter/tribal-water-data-map-manual#22]

**Comment by AHolder1** [comment]
@Josh-d89 - can you please confirm whether this issue is referring to the same info as in the following issue? If so, go ahead and add a comment here and close this issue. Thanks! 

https://github.com/CAWaterBoardDataCenter/tribal-water-data-map-manual/issues/7

**Comment by Josh-d89** [comment]
Confirmed. This is related to the pesticides issue 

#7

**Comment by AHolder1** [comment]
Nice! Thanks for confirming, @Josh-d89! :)
