### ISSUE TITLE
Mapping workflow for adding a layer

### ISSUE THREAD

**Issue by Josh-d89** [CAWaterBoardDataCenter/tribal-water-data-map-manual#31]
The following describes the workflow used to add a layer to the Tribal Water Data Map and User Manual.

**Add a layer to the _Internal_ map**

_Researching Layers_
1.	Identify or confirm the need for the layer with Tribal partners.
2.	Research/Find the appropriate data.
a.	Sometimes it’s easy to find layers in ArcGIS online.
i.	Make sure you’re logged in as OIMA_Mapper.
ii.	Open the map.
iii.	Click “Add”.
iv.	You can search “organization” and see other state agency hosted layers.
v.	You can also search “ArcGIS Online”, just be cognizant of the source, completeness, and age of the data.
b.	Find layers in the [California Open Data Portal](https://data.ca.gov/).
i.	Download the file, or use a URL.
1.	Use GeoJSON or Shapefile.
c.	Find data through online research that can be used to create your own layer.

_Adding Layers to GIS Map_
3.	To create layer, go to “home” on top left of the ArcGIS Online portal.
a.	Click “content”.
b.	Click “add item”
i.	If you are adding a layer through a URL, click “URL”.
ii.	If you are adding a layer from a file, click “feature layer”.
1.	Or you can drag and drop on the screen.
c.	After the file is added, now you can edit the page.

_Editing Layer Page_
i.	Change the title.
ii.	Change the description.
iii.	Change the header.
d.	Go back to the map and add the layer using
i.	“add”
ii.	“search”
iii.	“my content”
e.	Check that it functions properly.
f.	Click the three colored symbols below the layer to adjust how you want the data displayed.
g.	Click the three dots at the bottom of the layer name and rename it following it’s position in the layer guide (ex. 3.5.1. – Non-private_Land_Holders).
h.	Take a screen shot with just the new layer displayed.
i.	Create a thumbnail following the procedures in the powerpoint file titled "TribalWaterDataThumbnails"
j.	Go back to the more details page for that layer and add the thumbnail.
k.	Before saving, 
i.	Zoom back out to the whole state.
ii.	Check the top 2 layers (Waterboard Boundaries, Indigenous Territories)
l.	Save

**Push your edits to the _Public_ map [@Lbenton114 please add more details here, as appropriate]**

1. Email GIS and ask them to approve your recent updates and push them to the live map
2. Once GIS confirms the edits are live, verify that the changes can be seen on the [public map](https://gispublic.waterboards.ca.gov/portal/home/item.html?id=a71c1841907240e1a4d896c8cf2302a8).

**Update the [User Manual's Layer Guide](https://cawaterboarddatacenter.github.io/tribal-water-data-map-manual/layer-guide.html)**
_Recommend completing this step while DIT is making the revisions public_
1. Open the Map Project in R Studio
2. Pull
3. Open the Layer Guide .qmd
4. Go to the section the layer most appropriately fits.
5. Add the layer info to the section with the following format:
    a.	Name of layer
    b.	TLDR description
    c.	More detailed description
    d.	Screenshot
    e.	Source
6. Save
7. Commit (add a commit message describing your changes!)
8. Push
9. Verify that changes are public

**Update the GitHub Issue Status**
If the revision was associated with an Issue in the Project...

1. Navigate to the [Project](https://github.com/orgs/CAWaterBoardDataCenter/projects/8)
2. Find the Issue
3. Close the issue (add a comment before closing, if appropriate)

**Comment by AHolder1** [comment]
@Lbenton114 - please add a comment to this issue and spell the basic steps for adding a layer to the Tribal Water Data Map via API

**Comment by Lbenton114** [comment]
I mapped the work flow for Github, MapViewer, ArcGIS Pro, and R at [this link](https://docs.google.com/document/d/1KNMSoBJsL7RqDR_-Hv7I0EV9f4YpBudhhE2x61e4SKg/edit?usp=sharing)

**Comment by kevinjsong** [comment]
Created .qmd in repo! (workflow-guide)
