### ISSUE TITLE
Embed map into Tribal Water Data Initiatives Website

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/tribal-water-data-map-manual#38]
Hi @Lbenton114 - can you work with DIT to get the Tribal Water Data Map embedded into the [Tribal Water Data Initiatives Webpage](https://www.waterboards.ca.gov/resources/oima/tribal_water_data_initiatives/)? 

I think all it will take is a request to the HelpDesk and some instructions on where to put the map, which should be - "below the paragraph in the grey box and above the blue Tribal Water Data Initiatives box"

**Deadline:** If we could get this up by Oct 10 that would be great! 

Add a comment below if you have questions - and thanks! :)

**Comment by Lbenton114** [comment]
Emailed DIT to embed the Tribal Water Data Map into the Tribal Water Data Initiatives Webpage

**Comment by Lbenton114** [comment]
The map is embedded with the website. Just as a reminder, if you edit the public map and save it. That will alter the map on the Tribal Water Data Initiatives Website.

If you need to change the layers (i.e name, transparency) you do not need to contact DIT, we can do that ourselves and then click save.
