### ISSUE TITLE
Make Tribal Water Data Map Project Public

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/tribal-water-data-map-manual#4]
Hi @jpasner ! 

When you get a second (seriously, no rush!) - can you please make the [Tribal Water Data Map Project](https://github.com/orgs/CAWaterBoardDataCenter/projects/8) associated with this manual public? 

It will be important for us to be able to show our Tribal partners our progress on this over time, and the easiest way to do that will be to share the project link with them. 

Let me know if you have questions - and thanks so much! :)

**Comment by AHolder1** [comment]
Hi @jpasner ! Is it possible to have this completed by Oct 23rd? I am hoping to present the during the [Tribal Conference](https://tribalepa.com/2023-conference/) Oct 24-26, and I would like folks to be able to look at the Project during a workshop. Thanks! :)

**Comment by AHolder1** [comment]
Hi @jpasner - just a reminder to please make this project public soon, if you can. Also tagging @AndrewDHill just in case they can make the change to the settings, too! :) Thanks y'all!

**Comment by jpasner** [comment]
Hey @AHolder1 - sorry for the slow response, I forgot these notifications are going to my personal email, I need to fix that! As for your request, I've just made the project public. Please let me know if you want anything else changed 🎉

**Comment by AHolder1** [comment]
Woooo hooooo!!!  Thanks Jake - you ROCK! Making this project public was the last step we needed to take to complete the transparency loop - thanks for your help!
