### ISSUE TITLE
Add Groundwater Sustainability Agency (GSA) Boundaries

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/tribal-water-data-map-manual#46]
Requested by OPP
Be sure to check in with SGMA team 
Potential to get layers directly from [SGMA Data Viewer](https://sgma.water.ca.gov/webgis/?appid=SGMADataViewer#currentconditions)

**Comment by kevinjsong** [comment]
https://data.ca.gov/dataset/i03-groundwater-sustainability-agencies-mapservice

**Comment by kevinjsong** [comment]
Added via https://gispublic.waterboards.ca.gov/portal/home/item.html?id=2c69263c8958494abfce7591bf1761f2
